src/ExpenseTracker.Web/ViewModels/Workspace/WorkspaceIndexViewModel.cs
using System.Collections.Generic;

namespace ExpenseTracker.Web.ViewModels.Workspace
{
    public class WorkspaceIndexViewModel
    {
        public string Name { get; set; }
        public IList<Core.Entities.Workspace> Workspaces { get; set; }
    }
}

src/ExpenseTracker.Web/ViewModels/Workspace/WorkspaceViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ExpenseTracker.Core.Entities.Common;

namespace ExpenseTracker.Web.ViewModels.Workspace
{
    public class WorkspaceViewModel
    {
        [Display(Name = "Workspace Name")]
        [Required]
        [MinLength(3)]
        public string WorkspaceName { get; set; }

        [Display(Name="Color")]
        public string Color { get; set; }
        
        public readonly Dictionary<string, string> ColorList = Colors.GetColors;

        [Display(Name = "Description")]
        public string? Description { get; set; }
        
    }
}

src/ExpenseTracker.Web/Controllers/TransactionCategoryController.cs
using System;
using System.Threading.Tasks;
using ExpenseTracker.Core.Dto.TransactionCategory;
using ExpenseTracker.Core.Exceptions;
using ExpenseTracker.Core.Repositories.Interface;
using ExpenseTracker.Core.Services.Interface;
using ExpenseTracker.Infrastructure.Extensions;
using ExpenseTracker.Web.ViewModels.TransactionCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ExpenseTracker.Web.Controllers
{
    [Authorize]
    public class TransactionCategoryController : Controller
    {
        private readonly ITransactionCategoryRepository _transactionCategoryRepository;
        private readonly ITransactionCategoryService _transactionCategoryService;
        private readonly ILogger<TransactionCategoryController> _logger;

        public TransactionCategoryController(ITransactionCategoryRepository transactionCategoryRepository,
            ITransactionCategoryService transactionCategoryService,
            ILogger<TransactionCategoryController> logger)
        {
            _transactionCategoryRepository = transactionCategoryRepository;
            _transactionCategoryService = transactionCategoryService;
            _logger = logger;
        }
        
        public async Task<IActionResult> Index(TransactionCategoryIndexViewModel transactionCategoryIndexViewModel)
        {
            var transactionCategories = await _transactionCategoryRepository.GetAllAsync().ConfigureAwait(true);
            transactionCategoryIndexViewModel.TransactionCategories = transactionCategories;
            return View(transactionCategoryIndexViewModel);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            var transactionCategoryViewModel = new TransactionCategoryViewModel();
            return View(transactionCategoryViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransactionCategoryViewModel transactionCategoryViewModel)
        {
            try
            {
                if (!ModelState.IsValid) return View(transactionCategoryViewModel);

                await _transactionCategoryService.Create(new TransactionCategoryCreateDto()
                {
                    
                    Color = transactionCategoryViewModel.Color,
                    Type = transactionCategoryViewModel.Type,
                    Name = transactionCategoryViewModel.Name,
                    Icon = transactionCategoryViewModel.Icon
                });
            
                this.AddSuccessMessage("Transaction Category Create Successfully");
                
            }
            catch (Exception e)
            {
                _logger.LogError(e,e.Message);
                this.AddErrorMessage(e.Message);
            }
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Edit(int transactionCategoryId)
        {
            try
            {
                var transactionCategory = await _transactionCategoryRepository.GetByIdAsync(transactionCategoryId)
                    .ConfigureAwait(true) ?? throw new TransactionCategoryNotFoundException();

                var transactionViewModel = new TransactionCategoryViewModel()
                {
                    TransactionCategoryId = transactionCategory.TransactionCategoryId,
                    Name = transactionCategory.CategoryName,
                    Icon = transactionCategory.Icon,
                    Type = transactionCategory.Type,
                    Color = transactionCategory.Color
                };
            
                return View(transactionViewModel);
            }
            catch (Exception e)
            {
                _logger.LogError(e,e.Message);
                this.AddErrorMessage(e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TransactionCategoryViewModel transactionCategoryViewModel)
        {
            try
            {
                if (!ModelState.IsValid) return View(transactionCategoryViewModel);

                await _transactionCategoryService.Update(new TransactionCategoryUpdateDto()
                {
                    TransactionCategoryId = transactionCategoryViewModel.TransactionCategoryId,
                    Color = transactionCategoryViewModel.Color,
                    Type = transactionCategoryViewModel.Type,
                    Name = transactionCategoryViewModel.Name,
                    Icon = transactionCategoryViewModel.Icon
                });
            
                this.AddSuccessMessage("Transaction Category Updated Successfully");
                
            }
            catch (Exception e)
            {
                _logger.LogError(e,e.Message);
                this.AddErrorMessage(e.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int transactionCategoryId)
        {
            try
            {
                var transactionCategory = await _transactionCategoryRepository.GetByIdAsync(transactionCategoryId)
                    .ConfigureAwait(true) ?? throw new TransactionCategoryNotFoundException();

                await _transactionCategoryService.Delete(transactionCategory.TransactionCategoryId)
                    .ConfigureAwait(true);
                
                this.AddSuccessMessage("Transaction Category Deleted Successfully");
            }
            catch (Exception e)
            {
                _logger.LogError(e,e.Message);
                this.AddErrorMessage(e.Message);
            }
            return RedirectToAction(nameof(Index));
        }
        
        
        
    }
}

src/ExpenseTracker.Web/Controllers/TransactionController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using ExpenseTracker.Core.Dto.Transaction;
using ExpenseTracker.Core.Dto.TransactionCategory;
using ExpenseTracker.Core.Exceptions;
using ExpenseTracker.Core.Repositories.Interface;
using ExpenseTracker.Core.Services.Interface;
using ExpenseTracker.Infrastructure.Extensions;
using ExpenseTracker.Web.ViewModels;
using ExpenseTracker.Web.ViewModels.Transaction;
using ExpenseTracker.Web.ViewModels.TransactionCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ExpenseTracker.Web.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly ITransactionCategoryRepository _transactionCategoryRepository;
        private readonly ITransactionRepository _transactionRepository;
        private readonly ILogger<TransactionController> _logger;

        public TransactionController(ITransactionService transactionService,
            ITransactionCategoryRepository transactionCategoryRepository,
            ITransactionRepository transactionRepository,
            ILogger<TransactionController> logger)
        {
            _transactionService = transactionService;
            _transactionCategoryRepository = transactionCategoryRepository;
            _transactionRepository = transactionRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index(TransactionIndexViewModel transactionIndexViewModel)
        {
            var DefaultWorkspaceToken = (await this.GetCurrentUser()).DefaultWorkspace.Token;
            var transactions = _transactionRepository.GetPredicatedQueryable(a=>a.Workspace.Token == DefaultWorkspaceToken).OrderByDescending(x => x.TransactionDate).ToList();
            transactionIndexViewModel.Transactions = transactions;
            return View(transactionIndexViewModel);
        }

        public async Task<IActionResult> Create()
        {
            var transactionViewModel = new TransactionViewModel
            {
                TransactionCategories = await _transactionCategoryRepository.GetAllAsync().ConfigureAwait(true)
            };
            return View(transactionViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransactionViewModel transactionViewModel)
        {
            try
            {
                if (!ModelState.IsValid) return View(transactionViewModel);

                await _transactionService.Create(new TransactionCreateDto()
                {
                    UserId = this.GetCurrentUserId(),
                    WorkspaceToken = (await this.GetCurrentUser()).DefaultWorkspace.Token, 
                    TransactionDate = transactionViewModel.TransactionEntryDate,
                    Amount = transactionViewModel.TransactionAmount,
                    TransactionCategoryId = transactionViewModel.TransactionCategoryId,
                    Type = transactionViewModel.Type,
                    Description = transactionViewModel.Description
                });
                
                this.AddSuccessMessage("Transaction Created Successfully");
            }
            catch (Exception e)
            {
                _logger.LogError(e,e.Message);
                this.AddErrorMessage(e.Message);
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int Id)
        {
            try
            {
                var transaction = await _transactionRepository.GetByIdAsync(Id)
                    .ConfigureAwait(true) ?? throw new TransactionNotFoundException();

                var transactionViewModel = new TransactionViewModel()
                {
                  
                
                    Amount = transaction.Amount,
                   

                };

                return View(transactionViewModel);
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                this.AddErrorMessage(e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TransactionViewModel transactionViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {

                    await _transactionService.Update(new TransactionUpdateDto()
                    {

                        Amount = transactionViewModel.Amount,
                        Id=transactionViewModel.Id,


                    });
                }
                this.AddSuccessMessage("Transaction  Updated Successfully");

            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                this.AddErrorMessage(e.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            try
            {
                var transaction = await _transactionRepository.GetByIdAsync(Id)
                    .ConfigureAwait(true) ?? throw new TransactionNotFoundException();

                await _transactionService.Delete(transaction.Id)
                    .ConfigureAwait(true);

                this.AddSuccessMessage("Transaction  Deleted Successfully");
            }
            catch (Exception e)
            {
                _logger.LogError(e, e.Message);
                this.AddErrorMessage(e.Message);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

src/ExpenseTracker.Web/Controllers/WorkspaceController.cs
using System;
using System.Threading.Tasks;
using ExpenseTracker.Core.Dto.Workspace;
using ExpenseTracker.Core.Entities;
using ExpenseTracker.Core.Repositories.Interface;
using ExpenseTracker.Core.Services.Interface;
using ExpenseTracker.Infrastructure.Extensions;
using ExpenseTracker.Infrastructure.SessionFactory;
using ExpenseTracker.Web.ViewModels.Workspace;
using Microsoft.AspNetCore.Mvc;
using NHibernate;

namespace ExpenseTracker.Web.Controllers
{
    public class WorkspaceController : Controller
    {
        private readonly IWorkspaceService _workspaceService;
        private readonly IWorkspaceRepository _workspaceRepository;

        public WorkspaceController(IWorkspaceService workspaceService,IWorkspaceRepository workspaceRepository)
        {
            _workspaceService = workspaceService;
            _workspaceRepository = workspaceRepository;
        }
        // GET
        public async Task<IActionResult> Index(string name)
        {
            var workspaceViewModel = new WorkspaceIndexViewModel
            {
                Workspaces = await _workspaceRepository.GetAllAsync().ConfigureAwait(true)
            };
            return View(workspaceViewModel);
        }

        public IActionResult Create()
        {
            var workspaceViewModel = new WorkspaceViewModel();
            return View(workspaceViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(WorkspaceViewModel workspaceViewModel)
        {
            try
            {
                if (!ModelState.IsValid) return View(workspaceViewModel);

                var currentUser = await this.GetCurrentUser().ConfigureAwait(true);
                var workspaceDto = new WorkspaceCreateDto()
                {
                    UserId = currentUser.UserId,
                    Color = workspaceViewModel.Color,
                    Name = workspaceViewModel.WorkspaceName,
                    Description = workspaceViewModel.Description
                };
                
                await _workspaceService.Create(workspaceDto).ConfigureAwait(true);

                BaseSessionFactory.HttpContextAccessor?.HttpContext?.Session.SetDefaultWorkspace(currentUser.DefaultWorkspace.Token);
                
                var defaultWorkspace = BaseSessionFactory.HttpContextAccessor?.HttpContext?.Session.GetDefaultWorkspace();
                
                this.AddSuccessMessage("Workspace Created Successfully.");
            }
            catch (Exception e)
            {
                this.AddErrorMessage(e.Message);
            }
            
            return RedirectToAction(nameof(Index),"Home");
        }

        public async Task<IActionResult> ChangeDefault(string workspaceToken,string redirectUrl="/")
        {
            try
            {
                await _workspaceService.ChangeDefault(workspaceToken).ConfigureAwait(true);
            
                this.AddSuccessMessage("Workspace Changed Successfully");
            }
            catch (Exception e)
            {
                this.AddErrorMessage(e.Message);
            }

            return LocalRedirectPreserveMethod(redirectUrl);
        }
        
    }
}

src/ExpenseTracker.Web/Views/Workspace/Create.cshtml
@model ExpenseTracker.Web.ViewModels.Workspace.WorkspaceViewModel
@{
    ViewData["Title"] = "Workspace";
    Layout = "_LayoutSecondary";
}

<div class="page page-center">
    <div class="container-tight py-4">
        <div class="text-center mb-4">
            <a href=".">
                <img src="~/static/expense-tracker-logo.svg" height="36" alt="">
            </a>
        </div>
        <form asp-action="Create" asp-controller="Workspace">
        <div class="card card-md">
            <div class="card-body text-center py-4 p-sm-5">
                <img src="~/static/illustrations/undraw_sign_in_e6hj.svg" height="128" class="mb-n2" height="120" alt="">
                <h1 class="mt-5">Welcome to Expense Tracker!</h1>
                <p class="text-muted">All you need is a workspace to get started.</p>
            </div>
            <div class="hr-text hr-text-center hr-text-spaceless">Workspace</div>
            <div class="card-body">
                <div class="mb-3">
                    <label class="form-label" asp-for="WorkspaceName"></label>
                    <div class="input-group input-group-flat">
                        <span class="input-group-text">
                            @@
                        </span>
                        <input asp-for="WorkspaceName" class="form-control ps-1" autocomplete="off">
                    </div>
                    <div class="form-hint">Choose a Name that describes you or your business in a concise way. Make it short and easy to remember.</div>
                </div>
                <div class="mb-3">
                    @Html.LabelFor(a => a.Color, new { @class = "form-label col-3 col-form-label" })
                    <div class="row g-2">
                    @foreach (var color in Model.ColorList)
                    {
                        <div class="col-auto">
                            <label class="form-colorinput" title="@color.Key">
                                <input asp-for="Color" type="radio" value="@color.Value" class="form-colorinput-input" data-com.bitwarden.browser.user-edited="yes">
                                <span class="form-colorinput-color bg-@color.Key.ToLowerInvariant()"></span>
                            </label>
                        </div>
                    }
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Description"> Description (Optional)</label>
                    <div class="input-group input-group-flat">
                        <textarea asp-for="WorkspaceName" class="form-control ps-1" autocomplete="off"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="row align-items-center mt-3">
            <div class="col">
                <div class="btn-list justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        Continue
                    </button>
                </div>
            </div>
        </div>
        </form>
    </div>
</div>

src/ExpenseTracker.Web/Views/Workspace/Index.cshtml
@using ExpenseTracker.Core.Entities
@model ExpenseTracker.Web.ViewModels.Workspace.WorkspaceIndexViewModel

@{
    ViewBag.Title = "Workspace";
    Layout = "_Layout";
}

@section PageTitle
{
    <div class="page-header d-print-none">
        <div class="row align-items-center">
            <div class="col">
                <!-- Page pre-title -->
                <div class="page-pretitle">
                    Manage
                </div>
                <h2 class="page-title">
                    @ViewData["Title"]
                </h2>
            </div>
            <!-- Page title actions -->
            <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                    <a asp-action="Create" asp-controller="TransactionCategory" class="btn btn-primary d-none d-sm-inline-block">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
                        </svg>
                        Create New
                    </a>
                    <a asp-action="Create" asp-controller="TransactionCategory" class="btn btn-primary d-sm-none d-sm-inline-block btn-icon" aria-label="Create new Transaction Category">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
}

 <div class="row row-cards">
     <div class="col-12">
         <div class="card">
             <div class="table-responsive">
                 @if (Model.Workspaces.Any())
                 {
                     <table class="table card-table table-vcenter text-nowrap">

                         <thead>
                         <tr>
                             <th class="w-2">No.</th>
                             <th>Workspace Name</th>
                             <th>Token</th>
                             <th>Type</th>
                             <th>Action</th>
                         </tr>
                         </thead>
                         <tbody>


                         @foreach (var item in Model.Workspaces)
                         {
                             <tr>
                                 <td>
                                     <span class="text-muted">@item.WorkspaceId.ToString("D3")</span>
                                 </td>
                                 <td>
                                     <span class="avatar avatar-xs" style="background-color: @item.Color" ></span>
                                     <span class="text-muted">@item.WorkSpaceName</span>
                                 </td>
                                 <td>
                                     <span class="text-muted">@item.Token</span>
                                 </td>
                                 <td>
                                     @if (item.WorkspaceType == Workspace.TypeNormalWorkspace)
                                     {
                                         <span class="badge bg-gray">
                                             @Workspace.TypeNormalWorkspace
                                         </span>
                                     }
                                     else if (item.WorkspaceType == Workspace.TypeDefaultWorkspace)
                                     {
                                         <span class="badge bg-green">
                                             @Workspace.TypeDefaultWorkspace
                                         </span>
                                     }
                                 </td>
                                 <td>
                                     <a asp-action="ChangeDefault" asp-controller="Workspace" asp-route-workspaceToken="@item.Token" asp-route-redirectUrl="/Workspace" class="btn bth-default
                                     @if(item.IsDefault){ <text> disabled</text> }">
                                         <span class="nav-link-icon d-md-none d-lg-inline-block">
                                                                             <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                                 <path stroke="none" d="M0 0h24v24H0z" fill="none"/><polyline points="12 4 4 8 12 12 20 8 12 4"/><polyline points="4 12 12 16 20 12"/><polyline points="4 16 12 20 20 16"/>
                                                                             </svg>
                                                                         </span> Switch to workspace
                                     </a>
                                 </td>
                             </tr>
                         }

                         </tbody>
                     </table>
                 }
                 else
                 {
                     <div class="empty">
                         <div class="empty-img">
                             <img src="./static/illustrations/undraw_printing_invoices_5r4r.svg" height="128" alt="">
                         </div>
                         <p class="empty-title">Transactions Not Found.</p>
                         <p class="empty-subtitle text-muted">
                             Try adjusting your search or filter to find what you're looking for.
                         </p>
                         <div class="empty-action">
                             <a asp-action="Create" asp-controller="Transaction" class="btn btn-primary">
                                 <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                     <path stroke="none" d="M0 0h24v24H0z" fill="none"></path><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line>
                                 </svg>
                                 Create New
                             </a>
                         </div>
                     </div>
                 }
             </div>
         </div>
     </div>
 </div>